### ISSUE TITLE
Connect button doesn't works on Vivaldi web browser

### ISSUE THREAD

**Issue by Maxentr** [LaGuerrePiece/ChadGuard#3]
First of all, hello to everyone,

I installed the extension on my Vivaldi web browser and tried to link my discord account with the extension but the pop-up doesn't work. Below is a screen of the extension's console (the last line is displayed when I press the button). I don't know what access it's talking about since I've already whitelisted (from the ad blocker and tracker) the URL of the application on the browser and the extension has the rights for pop-ups and redirects (redirects work well).

It's probably the browser, but I prefer to point out the problem anyway.

Console: 
![image](https://user-images.githubusercontent.com/67283154/161856368-ad305e61-75e6-4d37-b52b-9c06c23592fc.png)

My Vivaldi: 
<html>
<body>

Vivaldi | 5.1.2567.73 (Stable channel) (64 bits)
-- | --
Revision | dcad6d380887823962edf4339497ddacc2d6f519
Operating System | Windows 10 Version 21H2 (Build 19044.1586)
JavaScript | V8 9.8.177.13
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 Safari/537.36

</body>
</html>

**Comment by whiterqbbit** [comment]
Yeah, I also use Vivaldi and I have the exact same problem. I have yet to find how to fix it unfortunately :(

**Comment by Maxentr** [comment]
The bug has been fixed in Vivaldi version 5.2
