### ISSUE TITLE
Blockpages not working in incognito mode

### ISSUE THREAD

**Issue by 0xturboblitz** [LaGuerrePiece/ChadGuard#6]
In incognito mode, we noticed pages are blocked but blockpages (Stop_And_Reflect.html and Stop_And_Refocus.html) cannot be loaded.

Thoses blockpages are authorized in the web_accessible_resources section of manifest.json, but I suspect that incognito mode does not allow this type of redirection.

If someone has an idea, contact us or initiate a pull request !

**Comment by Maxentr** [comment]
I fixed this bug in this [pull request](https://github.com/LaGuerrePiece/ChadGuard/pull/10).
